name: Sync Wiki

on:
  workflow_dispatch: # Déclenchement manuel
  push:
    branches:
      - master
      - main
    paths:
      - "docs/**" # Surveille tout le dossier docs

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone wiki
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync docs with Wiki
        run: |
          # Copier tout le contenu du dossier docs vers le wiki
          cp -r docs/* wiki/
          cd wiki

          # Configuration Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Vérifier s'il y a des changements
          if [[ -n "$(git status --porcelain)" ]]; then
            # Ajouter et commiter les changements
            git add .
            git commit -m "📚 Docs: Synchronisation automatique depuis le dossier docs

            Mise à jour déclenchée par ${{ github.event_name }}
            Commit: ${{ github.sha }}"
            git push
          else
            echo "Aucun changement détecté dans le wiki"
          fi
